#!/usr/bin/python3
# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: 2005-2016 System76, Inc.

import json

from system76driver.model import get_all_dmi_info


info = get_all_dmi_info()
print(json.dumps(info, sort_keys=True, indent=4))
