#!/usr/bin/python3

# system76-driver: Universal driver for System76 computers
# Copyright (C) 2005-2013 System76, Inc.
#
# This file is part of `system76-driver`.
#
# `system76-driver` is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# `system76-driver` is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with `system76-driver`; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""
Test Airplane Mode workaround.
"""

import argparse
import os
import sys

from gi.repository import GLib

from system76driver.model import dmidecode
from system76driver.airplane import run_loop


GLib.threads_init()

parser = argparse.ArgumentParser()
parser.add_argument('--model', help='force model rather than detecting it')
args = parser.parse_args()
if os.getuid() != 0:
    sys.exit('Error: system76-daemon must be run as root')


if not args.model:
    args.model = dmidecode('system-version')
print('model:', args.model)


brightness = {
    'gazp9': '638\n',
}


filename = '/sys/class/backlight/intel_backlight/brightness'
if args.model in brightness:
    value = brightness[args.model]
    print('writting brightness {!r}'.format(value))
    open(filename, 'w').write(value)


mainloop = GLib.MainLoop()
mainloop.run()
