#!/usr/bin/python3

# system76-driver: Universal driver for System76 computers
# Copyright (C) 2005-2013 System76, Inc.
#
# This file is part of `system76-driver`.
#
# `system76-driver` is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# `system76-driver` is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with `system76-driver`; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""
Test Airplane Mode workaround.
"""

import time
start_time = time.monotonic()

import argparse
import os
import sys
import logging

from gi.repository import GLib

from system76driver.model import dmidecode
from system76driver.daemon import run_airplane, run_brightness, load_json_conf


logging.basicConfig(
    level=logging.DEBUG,
    style='{',
    format='{asctime}  {levelname}  {message}',
)
log = logging.getLogger()
GLib.threads_init()
parser = argparse.ArgumentParser()
parser.add_argument('--model', help='force model rather than detecting it')
args = parser.parse_args()
if os.getuid() != 0:
    sys.exit('Error: system76-daemon must be run as root')

log.info('**** Process start at monotonic time %r', start_time)
if not args.model:
    #_model = load_json_conf('/etc/system76-daemon.json').get('model')
    #args.model = (_model or dmidecode('system-version'))
    args.model = dmidecode('system-version')

log.info('model: %s', args.model)
brightness = run_brightness(args.model)
airplane = run_airplane(args.model)

mainloop = GLib.MainLoop()
mainloop.run()
