#!/usr/bin/python3

# system76-driver: Universal driver for System76 computers
# Copyright (C) 2005-2016 System76, Inc.
#
# This file is part of `system76-driver`.
#
# `system76-driver` is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# `system76-driver` is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with `system76-driver`; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""
Update firmware.
"""

import time
start_time = time.monotonic()
import argparse
import os
import sys
import logging

from gi.repository import GLib

import system76driver
from system76driver import firmware

NOTIFICATION_TIMEOUT = 24*60*60 # 24 hours

logging.basicConfig(
    level=logging.DEBUG,
    style='{',
    format='{asctime}  {levelname}  {message}',
)
log = logging.getLogger()

parser = argparse.ArgumentParser()
parser.add_argument('--reinstall', action='store_true', help='install latest firmware even if its already installed')
parser.add_argument('--debug', action='store_true', default=False,
    help='print loaded modules',
)
args = parser.parse_args()

if os.getuid() != 0:
    sys.exit('Error: system76-daemon must be run as root')
log.info('**** Process start at monotonic time %r', start_time)

start_time = time.time()
updater = firmware.run_firmware_updater(args.reinstall)
end_time = time.time()

#Delay exit until notification timeout
if end_time < start_time + NOTIFICATION_TIMEOUT:
    log.info((start_time + NOTIFICATION_TIMEOUT) - end_time)
    time.sleep((start_time + NOTIFICATION_TIMEOUT) - end_time)
print('firmware-exit')
