#!/usr/bin/python3

# system76-driver: Universal driver for System76 computers
# Copyright (C) 2005-2016 System76, Inc.
#
# This file is part of `system76-driver`.
#
# `system76-driver` is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# `system76-driver` is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with `system76-driver`; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""
Update firmware.
"""

import time
import argparse
import os
import sys
import logging

from system76driver.firmware import run_firmware_updater

NOTIFICATION_TIMEOUT = 24*60*60 # 24 hours

logging.basicConfig(
    filename='/var/log/system76-driver.log',
    level=logging.DEBUG,
    style='{',
    format='{asctime}  {levelname}  {message}',
)
log = logging.getLogger()

parser = argparse.ArgumentParser()
parser.add_argument('--reinstall', action='store_true', help='install latest firmware even if its already installed')
parser.add_argument('--notification', action='store_true', help='show notification if firmware not up to date')
args = parser.parse_args()

if os.getuid() != 0:
    sys.exit('Error: system76-firmware must be run as root')

start_time = time.time()
updater = run_firmware_updater(reinstall=args.reinstall, notification=args.notification)
end_time = time.time()

#Delay exit until notification timeout
if args.notification and end_time < start_time + NOTIFICATION_TIMEOUT:
    log.info((start_time + NOTIFICATION_TIMEOUT) - end_time)
    time.sleep((start_time + NOTIFICATION_TIMEOUT) - end_time)
