#!/usr/bin/python3
# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: 2005-2017 System76, Inc.

"""
Backlight daemon to workaround incompatibility between GNOME and NVIDIA 9 Series.
"""

import time
start_time = time.monotonic()
import argparse
import os
import sys
import logging

from gi.repository import GLib
from gi.repository import GObject

import system76driver
from system76driver import daemon, userdaemon
from system76driver.daemon import load_json_conf


logging.basicConfig(
    level=logging.DEBUG,
    style='{',
    format='{asctime}  {levelname}  {message}',
)
log = logging.getLogger()

parser = argparse.ArgumentParser()
parser.add_argument('--model', help='force model rather than detecting it')
parser.add_argument('--debug', action='store_true', default=False,
    help='print loaded modules',
)
args = parser.parse_args()

if os.getuid() == 0:
    sys.exit('Error: system76-daemon must be run as user')
log.info('**** Process start at monotonic time %r', start_time)

if not args.model:
    model = daemon.load_json_conf('/etc/system76-daemon.json').get('model')
    args.model = (model or system76driver.get_product_version())
log.info('model: %r', args.model)
userdaemon.run_backlight(args.model)

mainloop = GLib.MainLoop()
if args.debug:
    names = sorted(sys.modules)
    for name in names:
        print(name)
    print(len(names))
mainloop.run()
