#!/bin/sh

# This file (or a link to it) must be in the folder /lib/systemd/system-sleep/
# Purpose: reset theme and background after resuming from suspend
# This will fix bad window borders and backgrounds caused by Nvidia driver 375.39.

echo "fix $*"

if [ "$2" = "suspend" ] || [ "$2" = "hybrid-sleep" ]; then
    case "$1" in
        pre) true ;;
        post)

    FGUSER="$(w -h | grep "tty$(sudo fgconsole)"  | cut -d ' ' -f1)"
    echo "fix FGUSER: $FGUSER"
    
    sleep 2
    
    BACKGROUND="$(su - "$FGUSER" -c 'gsettings get org.gnome.desktop.background picture-uri')"
    GTK="$(su - "$FGUSER" -c 'gsettings get org.gnome.desktop.interface gtk-theme')"

    echo "fix: Start $BACKGROUND $GTK"
    su - "$FGUSER" -c "gsettings set org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/ override-decoration-theme true"
    su - "$FGUSER" -c "gsettings set org.gnome.desktop.interface gtk-theme ''"
    su - "$FGUSER" -c "gsettings set org.gnome.desktop.background picture-uri ''"
    
    sleep 1
    
    su - "$FGUSER" -c "gsettings set org.gnome.desktop.background picture-uri $BACKGROUND"
    su - "$FGUSER" -c "gsettings set org.gnome.desktop.interface gtk-theme $GTK"
    
    sleep 1
    
    su - "$FGUSER" -c "gsettings set org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/ override-decoration-theme false"
    
    BACKGROUND="$(su - "$FGUSER" -c 'gsettings get org.gnome.desktop.background picture-uri')"
    GTK="$(su - "$FGUSER" -c 'gsettings get org.gnome.desktop.interface gtk-theme')"

    echo "fix: Done $BACKGROUND $GTK"
    ;;
esac
fi

