#!/bin/sh

case "$1" in
    hibernate|suspend)
        rmmod rtl8187
        sleep 0
        ;;
    thaw|resume)
        modprobe rtl8187
        iwconfig wlan0 rate 5.5M fixed
        ;;
    *) exit $NA
        ;;
esac