/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainWindow (void);
GtkWidget* create_aboutDialog (void);
GtkWidget* create_restoreDialog (void);
GtkWidget* create_restoreComplete (void);
GtkWidget* create_driverDialog (void);
GtkWidget* create_driverComplete (void);
GtkWidget* create_noDrivers (void);
GtkWidget* create_unsupported (void);
